### ISSUE TITLE
[Feature] Inline prop definition inside component signature

### ISSUE THREAD

**Issue by wrapperup** [Pitasi/rscx#1]
I've been toying with this library, and it's a lot of fun. I've been looking for some kind of templating that supported context dependency injection like Leptos, awesome stuff!

It looks like this is planned from reading the source, but having props defined in the function signature to generate the Props struct, just like Leptos, would be nice. I'd love to make a PR for this if you're interested in help.

**Comment by Pitasi** [comment]
Sure, feel free to do it! I'll be glad to accept a contribution 😁

**Comment by thomaseizinger** [comment]
I also want this! I'll see if I can hack a PR together :)
