### ISSUE TITLE
Speed up void element detection 1.7–30x

### ISSUE THREAD

**Issue by Nick-Mazuk** [Pitasi/rscx#2]
Currently void element detection uses a hash map. However arrays are almost always faster when dealing with few items (even though the time complexity is O(n)).

https://github.com/Pitasi/rscx/blob/e7d1e792527415db8f23a1b9e3f13a1dbf5a767b/rscx-macros/src/lib.rs#L23-L31

So replacing the current code with the following array is much faster:

```rust
const VOID_TAGS: [&str; 14] = [
    "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source",
    "track", "wbr",
];
```

## Potential other improvements

Since the array is traversed from beginning to end, you can put the most common tags at the beginning to minimize the number of lookups.

While I couldn't find any strong data on the most common tags, I'd suspect it'd be something like this:

```rust
const VOID_TAGS: [&str; 14] = [
    "img", "input", "meta", "link", "hr", "br", "source", "track", "wbr", "area", "base", "col",
    "embed", "param",
];
```

## Benchmarks

I wrote up a quick benchmark to demonstrate the difference. At worst the array is 70% faster. At best it's 30x faster.

```rust
extern crate criterion;

use criterion::{black_box, criterion_group, criterion_main, Criterion};

pub fn criterion_benchmark(c: &mut Criterion) {
    let tags_arr = [
        "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param",
        "source", "track", "wbr",
    ];
    let tags_set: std::collections::HashSet<&str> = tags_arr.iter().copied().collect();
    c.bench_function("array first", |b| {
        b.iter(|| black_box(tags_arr.iter().any(|&x| x == "area")))
    });
    c.bench_function("array last", |b| {
        b.iter(|| black_box(tags_arr.iter().any(|&x| x == "wbr")))
    });
    c.bench_function("set first", |b| {
        b.iter(|| black_box(tags_set.contains("area")))
    });
    c.bench_function("set last", |b| {
        b.iter(|| black_box(tags_set.contains("wbr")))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

```
array first             time:   [504.87 ps 505.23 ps 505.72 ps]
Found 11 outliers among 100 measurements (11.00%)
  4 (4.00%) high mild
  7 (7.00%) high severe

array last              time:   [8.0767 ns 8.0819 ns 8.0889 ns]
Found 13 outliers among 100 measurements (13.00%)
  4 (4.00%) high mild
  9 (9.00%) high severe

set first #2          time:   [13.737 ns 13.743 ns 13.750 ns]
Found 9 outliers among 100 measurements (9.00%)
  2 (2.00%) high mild
  7 (7.00%) high severe

set last #2           time:   [15.542 ns 15.554 ns 15.569 ns]
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  6 (6.00%) high severe
```

P.S. I believe the improvement is real and not from LLVM optimize out the array traversal because the first/last element lookup times are vastly different. If LLVM did optimize out the array traversal, then we would expect the first/last element lookups to have very similar times.

**Comment by Pitasi** [comment]
Thanks for the well explained issue!

I honestly copied over that code the example of rstml, in fact, they need a HashSet parameter in this function call: https://github.com/rs-tml/rstml/blob/b80cc393794ff96e27ba9384f9cb3ba9bd77ddac/src/config.rs#L95.

But instead of using the HashMap internally in rscx too (in the walk_node fn), we can use a different approach like you suggested.

I tried writing a function like this instead of using arrays:

```rs
fn is_empty_element(name: &str) -> bool {
    match name {
        "area" | "base" | "br" | "col" | "embed" | "hr" | "img" | "input" | "link" | "meta"
        | "param" | "source" | "track" | "wbr" => true,
        _ => false,
    }
}
```

And, it looks slightly faster and more "stable":

```
array first             time:   [504.81 ps 505.35 ps 506.08 ps]

array last              time:   [8.0688 ns 8.0725 ns 8.0778 ns]

pattern match first     time:   [372.35 ps 373.80 ps 375.38 ps]

pattern match last      time:   [369.48 ps 370.03 ps 370.78 ps]

set first               time:   [9.8162 ns 9.8693 ns 9.9197 ns]

set last                time:   [10.478 ns 10.489 ns 10.503 ns]
```

I'm not sure if build times are going to be that much faster but it's a low hanging fruit, thanks for bringing this up :)
