### ISSUE TITLE
`Option`s are not handled very well

### ISSUE THREAD

**Issue by thomaseizinger** [Pitasi/rscx#4]
I might be missing something but rendering an `Option` doesn't work very well at the moment as one has to always append `.unwrap_or_default()` to construct an empty `String`.

Is it possible to make that implicit and just omit rendering if the `Option` is `None`?

**Comment by Pitasi** [comment]
Yeah, I struggled a bit with that as well, it's too verbose right now.

I've been thinking about this problem and maybe what would make sense is to have a `trait Render` that is implemented for pretty much all the types (including Options), like Maud does. It will also help when we'll finally get opt-out HTML escaping.

It's slightly annoyed that one would no longer return a `String` from their components' functions (I liked the simplicity of that), but it's for the best.

**Comment by thomaseizinger** [comment]
> It's slightly annoyed that one would no longer return a `String` from their components' functions (I liked the simplicity of that), but it's for the best.

To be honest, coming from https://github.com/render-rs/render.rs, I was surprised that I need to specify a return type at all. The macro could just set the correct type!

**Comment by Pitasi** [comment]
never heard of render.rs before (how many of these exist? 🤯), I must take a look

**Comment by thomaseizinger** [comment]
> never heard of render.rs before (how many of these exist? 🤯), I must take a look

It has the best ergonomics IMO (apart from the outdated syn parser) and it is unmaintained :(

**Comment by Maaarcocr** [comment]
I have a branch locally that tries to fix this. I'll put it up soon!
