### ISSUE TITLE
error: unknown start of token: \u{ff0c}

### ISSUE THREAD

**Issue by kzhui125** [Pitasi/rscx#8]
```rs
use rscx::html;

pub fn t1() {
    html! {
        <h1> 你好， 世界 </h1>
    };
}
```

https://www.htmlsymbols.xyz/unicode/U+FF0C

hello, I can't add a "Chinese comma" to a Chinese sentence, build failed.

the same as "。"

**Comment by Pitasi** [comment]
Hey, thanks for trying rscx and taking the time to report this!

The solution is to wrap your content in quotes, like a string:

```rs
use rscx::html;

pub fn t1() {
    html! {
        <h1>" 你好， 世界 "</h1>
    };
}
```

This is also valid for emojis. 

This behaviour comes from https://github.com/rs-tml/rstml, the underlying crate I'm using to parse the RSX syntax :)
